name: Eard
main: Eard\Main
version: 0.0.1
api:
  - 2.0.0
  - 3.0.0
  - 3.0.0-ALPHA5 #pmmp/PocketMine-MP
load: STARTUP
author: 32ki
description: Seikatu Server
website: http://eard.32ki.net/
commands:
 s:
  description: ""
  usage: "/s"
  permission: eard
 test:
  description: ""
  usage: "/test"
  permission: eard
  aliases: [test2, test3, test4, t]
 ap:
  description: "eard: AreaProtector"
  usage: "/ap [a|v|give]"
  permission: eard
 gv:
  description: "eard: Government"
  usage: "/gv [a|v|give]"
  permission: eard
 co:
  description: "eard: Connection"
  usage: "/co <number>"
  permission: eard
 db:
  description: "eard: DB"
  usage: "/co [addr|user|pass|name]"
  permission: eard
 ea:
  description: "eard: Earmazon"
  usage: "/ea [buy|sell|add]"
  permission: eard
 li:
  description: "eard: License"
  usage: "/li [give|confirm]"
  permission: eard
 enemy:
  description: "エネミーを呼び出します"
  usage: "/enemy <type>"
  permission: eard
 saveskin:
  description: "スキンをエンコードして保存します"
  usage: "/saveskin <name>"
  permission: eard
permissions:
 eard:
  default: op
  description: ""
  children:
   eard.command:
    default: true
    description: ""