name: Eard
main: Eard\Main
version: 0.0.1
api:
  - 2.0.0
  - 3.0.0
  - 3.0.0-ALPHA5 #pmmp/PocketMine-MP
load: STARTUP
author: 32ki
description: Seikatu Server
website: http://muni.32ki.net/
commands:
 s:
  description: ""
  usage: "/s"
  permission: muni
 test:
  description: ""
  usage: "/test"
  permission: muni
  aliases: [test2, test3, test4, t]
 ap:
  description: "Muni: AreaProtector"
  usage: "/ap [asec|vsec|give]"
  permission: muni
 gv:
  description: "Muni: Government"
  usage: "/gv [ameu|vmeu|give]"
  permission: muni
 co:
  description: "Muni: Connection"
  usage: "/co <number>"
  permission: muni
 db:
  description: "Muni: DB"
  usage: "/co [addr|user|pass|name]"
  permission: muni
 enemy:
  description: "エネミーを呼び出します"
  usage: "/enemy <type>"
  permission: muni
 saveskin:
  description: "スキンをエンコードして保存します"
  usage: "/saveskin <name>"
  permission: muni
permissions:
 muni:
  default: op
  description: ""
  children:
   muni.command:
    default: true
    description: ""